package com.hiskytechs.freemusicapi

data class DATAX(
    val ABSENCE_CATEGORY: String,
    val ABSENCE_ICON: String,
    val ABSENCE_TYPE_TEXT: String,
    val AWAY_PARTICIPANT3_CHAR_NAME: String,
    val AWAY_PARTICIPANT_LOGO_URL: String,
    val AWAY_PARTICIPANT_NAME: String,
    val AWAY_PARTICIPANT_URL: String,
    val AWAY_SCORE: Int,
    val AWAY_WIN: Boolean,
    val EVENT_ENCODED_ID: String,
    val EVENT_ID: String,
    val EVENT_START_TIME: String,
    val FLAG_ID: Int,
    val FLAG_NAME: String,
    val HOME_PARTICIPANT3_CHAR_NAME: String,
    val HOME_PARTICIPANT_LOGO_URL: String,
    val HOME_PARTICIPANT_NAME: String,
    val HOME_PARTICIPANT_URL: String,
    val HOME_SCORE: Int,
    val HOME_WIN: Boolean,
    val RATING: String,
    val RATING_RANK: Int,
    val STATS: STATS,
    val TOURNAMENT_SEASON: String,
    val TOURNAMENT_TEMPLATE_SHORT_CODE: String,
    val TOURNAMENT_TITLE: String,
    val TOURNAMENT_URL: String,
    val WIN_LOSE_CLASS_SUFFIX: String,
    val WIN_LOSE_SHORT: String,
    val WIN_LOSE_TITLE: String
)